filter:
    excluded_paths: [vendor/*, tests/*]
checks:
    php:
        code_rating: true
        duplication: true
before_commands:
    - "composer install --prefer-dist"
tools:
    php_mess_detector: true
    php_analyzer: true
    php_code_coverage: true
    php_pdepend: true
    sensiolabs_security_checker: true
    external_code_coverage: true 
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
